server:
  port: 8999
spring:
  application:
    name: hmdp
  rabbitmq:
    addresses: 117.72.91.159
    username: guest
    password: guest
    port: 5672
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.91.159:13306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: "123456"
  redis:
    host: 117.72.91.159
    port: 16379
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug